# Generated by Django 3.0.2 on 2020-01-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(blank=True, max_length=99, null=True)),
                ('initials', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_location', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'db_table': 'tb_location',
                'managed': True,
            },
        ),
    ]
