# Generated by Django 3.0.2 on 2020-01-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('levels', '0001_initial'),
        ('tbtypes', '0001_initial'),
        ('locations', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_requester', models.CharField(blank=True, max_length=99, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=99, null=True)),
                ('anydesk_number', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=45, null=True)),
                ('open_date', models.CharField(blank=True, max_length=99, null=True)),
                ('attached_img', models.CharField(blank=True, max_length=10, null=True)),
                ('open_hour', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='category.TbCategory')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels.TbLevel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.TbLocation')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='status.TbStatus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tbtypes.TbType')),
            ],
            options={
                'db_table': 'tb_ticket',
                'managed': True,
            },
        ),
    ]
